// PluginEditor.cpp
#include "PluginEditor.h"

// Binary data generated by juce_add_binary_data
#include "BinaryData.h"

PluginEditor::PluginEditor(PluginProcessor& p)
    : AudioProcessorEditor(&p), processor(p)
{
    // Match canvas size from Faceplate
    setSize(800, 600);
    // Initialize parameter tracking

    // Add browser to editor
    addAndMakeVisible(browser);
    // Initialize parameter tracking map
    for (auto* param : processor.getParameters())
    {
        if (auto* rangedParam = dynamic_cast<juce::AudioProcessorParameterWithID*>(param))
            lastSentValues[rangedParam->paramID] = rangedParam->getValue();
    }

    // Start timer for real-time parameter sync (30 Hz recommended)
    startTimerHz(30);

    // Navigate to index.html via resource provider
    browser.goToURL(browser.getResourceProviderRoot() + "index.html");
}

PluginEditor::~PluginEditor()
{
    stopTimer();
}

void PluginEditor::paint(juce::Graphics& g)
{
    g.fillAll(juce::Colours::black);
}

void PluginEditor::resized()
{
    browser.setBounds(getLocalBounds());
}

void PluginEditor::timerCallback()
{
    juce::Array<juce::var> changedParams;

    for (auto* param : processor.getParameters())
    {
        auto* rangedParam = dynamic_cast<juce::AudioProcessorParameterWithID*>(param);
        if (!rangedParam) continue;

        float currentValue = rangedParam->getValue();
        float& lastValue = lastSentValues[rangedParam->paramID];

        if (std::abs(currentValue - lastValue) > 0.0001f)
        {
            juce::DynamicObject::Ptr paramObj = new juce::DynamicObject();
            paramObj->setProperty("id", rangedParam->paramID);
            paramObj->setProperty("value", currentValue);
            changedParams.add(juce::var(paramObj.get()));
            lastValue = currentValue;
        }
    }

    if (!changedParams.isEmpty())
    {
        juce::DynamicObject::Ptr eventData = new juce::DynamicObject();
        eventData->setProperty("params", changedParams);
        browser.emitEventIfBrowserIsVisible("__juce__paramSync", juce::var(eventData.get()));
    }
}

std::optional<juce::WebBrowserComponent::Resource>
    PluginEditor::getResource(const juce::String& url)
{
    // Extract filename from URL
    auto filename = url.fromLastOccurrenceOf("/", false, false);

    // Map to binary data
    int dataSize = 0;
    const char* data = nullptr;
    juce::String mimeType;

    if (filename == "index.html")
    {
        data = BinaryData::index_html;
        dataSize = BinaryData::index_htmlSize;
        mimeType = "text/html";
    }
    else if (filename == "style.css")
    {
        data = BinaryData::style_css;
        dataSize = BinaryData::style_cssSize;
        mimeType = "text/css";
    }
    else if (filename == "components.js")
    {
        data = BinaryData::components_js;
        dataSize = BinaryData::components_jsSize;
        mimeType = "application/javascript";
    }
    else if (filename == "bindings.js")
    {
        data = BinaryData::bindings_js;
        dataSize = BinaryData::bindings_jsSize;
        mimeType = "application/javascript";
    }

    if (data != nullptr)
    {
        auto* byteData = reinterpret_cast<const std::byte*>(data);
        return juce::WebBrowserComponent::Resource {
            std::vector<std::byte>(byteData, byteData + dataSize),
            mimeType
        };
    }

    return std::nullopt;
}

void PluginEditor::handleSetParameter(
    const juce::Array<juce::var>& args,
    juce::WebBrowserComponent::NativeFunctionCompletion complete) const
{
    if (args.size() >= 2)
    {
        auto paramId = args[0].toString();
        auto value = static_cast<float>(args[1]);

        if (auto* param = processor.apvts.getParameter(paramId))
        {
            param->setValueNotifyingHost(value);
        }
    }
    complete({});
}

void PluginEditor::handleGetParameter(
    const juce::Array<juce::var>& args,
    juce::WebBrowserComponent::NativeFunctionCompletion complete) const
{
    if (args.size() >= 1)
    {
        auto paramId = args[0].toString();

        if (auto* param = processor.apvts.getParameter(paramId))
        {
            complete(param->getValue());
            return;
        }
    }
    complete(0.5f);
}

void PluginEditor::handleBeginGesture(
    const juce::Array<juce::var>& args,
    juce::WebBrowserComponent::NativeFunctionCompletion complete) const
{
    if (args.size() >= 1)
    {
        auto paramId = args[0].toString();

        if (auto* param = processor.apvts.getParameter(paramId))
        {
            param->beginChangeGesture();
        }
    }
    complete({});
}

void PluginEditor::handleEndGesture(
    const juce::Array<juce::var>& args,
    juce::WebBrowserComponent::NativeFunctionCompletion complete) const
{
    if (args.size() >= 1)
    {
        auto paramId = args[0].toString();

        if (auto* param = processor.apvts.getParameter(paramId))
        {
            param->endChangeGesture();
        }
    }
    complete({});
}

void PluginEditor::syncAllParametersToWebView()
{
    juce::Array<juce::var> params;

    for (auto* param : processor.getParameters())
    {
        auto* rangedParam = dynamic_cast<juce::RangedAudioParameter*>(param);
        if (!rangedParam) continue;

        juce::DynamicObject::Ptr paramObj = new juce::DynamicObject();
        paramObj->setProperty("id", rangedParam->paramID);
        paramObj->setProperty("value", rangedParam->getValue());
        params.add(juce::var(paramObj.get()));
    }

    juce::DynamicObject::Ptr eventData = new juce::DynamicObject();
    eventData->setProperty("params", params);
    browser.emitEventIfBrowserIsVisible("__juce__paramSync", juce::var(eventData.get()));
}